name = "JLCM"
uuid = "109d4626-9673-535f-b40a-ab415f4b888a"
version = "0.0.1"
authors = ["Matthias Brueckner <matthias.brueckner@posteo.de>"]

[deps]
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"

[compat]
julia = "^1"
DynamicHMC = "^1.0.0"
