name = "JLCM"
uuid = "3ce6fbc2-4cf9-4180-856b-1f5f021f4a7d"
version = "0.0.1"
authors = ["Matthias Brueckner <matthias.brueckner@posteo.de>"]

[deps]
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"

[compat]
julia = "^1"
DynamicHMC = "^1.0.0"
